### ISSUE TITLE
Incorrect dockerfile?

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/eos3ae6#12]
Hello @DhanshreeA I don't know why the dockerfile in the model repo is this one: https://github.com/ersilia-os/eos3ae6/blob/main/Dockerfile

**Comment by DhanshreeA** [comment]
This was an oversight on my part. This is happening because when the V2 build fails and we attempt the V1 build, at that point `Dockerfile` contains the build instructions, and `Dockerfile_legacy` contains the conda environment installs. When we place the V1 Dockerfile within the repo, the script overwrites `Dockerfile_legacy` with the V2 build Dockerfile. This isn't the only model where this is happening then, it will be 11 other models that got built the old way. I'll fix this ASAP.

**Comment by DhanshreeA** [comment]
This is now fixed - correct Dockerfile has been restored, and the workflows have been updated.
